{
	[1] = {
		["AllyID"] = 0,
		["AllyName"] = [[Alliance 1]],
		["IsHuman"] = true,
		["IsRequired"] = true,
		["TeamID"] = 0,
		["TeamName"] = [[PLAYER_NAME]],
		["Color"] = 16711680,
		["ColorR"] = 0,
		["ColorG"] = 0,
		["ColorB"] = 255,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
	[2] = {
		["AllyID"] = 1,
		["AllyName"] = [[Alliance 2]],
		["IsHuman"] = false,
		["IsRequired"] = false,
		["TeamID"] = 1,
		["TeamName"] = [[Enemy]],
		["Color"] = 255,
		["ColorR"] = 255,
		["ColorG"] = 0,
		["ColorB"] = 0,
		["AiShortName"] = [[NullAI]],
		["AiVersion"] = [[0.1]],
	},
}